version: "3"
services:
  dnscrypt-proxy-modns:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: jqtype/dnscrypt-proxy-modns
    container_name: dnscrypt-proxy-modns
    restart: always
    environment:
      - DEBUG=true
    ports:
      - "127.0.0.1:53:53/udp"
    #    expose:
    #      - "53"
    tty: true
    volumes:
      - ./log:/var/log/dnscrypt-proxy
      - ./config:/config
