name: Build and Publish Docker

on:
  push:
    branches:
      - multiple-relays

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: dnscrypt-proxy-modns
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          file: ./docker/Dockerfile

